# modules/report_utils.py
import os
import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import Table, TableStyle, SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

def generate_fairness_report(
    output_path: str,
    dataset_name: str,
    target_col: str,
    sensitive_feature: str,
    model_name: str,
    fairness_before: dict,
    fairness_after: dict,
    accuracy_before: float,
    accuracy_after: float,
):
    styles = getSampleStyleSheet()
    story = []
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    story.append(Paragraph("<b><font size=16 color='#2E86C1'>BiasScope Fairness Audit Report</font></b>", styles["Title"]))
    story.append(Paragraph(f"<b>Date Generated:</b> {timestamp}", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>1️⃣ Dataset Information</b>", styles["Heading2"]))
    story.append(Paragraph(f"<b>Dataset:</b> {dataset_name}", styles["Normal"]))
    story.append(Paragraph(f"<b>Target Column:</b> {target_col}", styles["Normal"]))
    story.append(Paragraph(f"<b>Sensitive Feature:</b> {sensitive_feature}", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>2️⃣ Model Information</b>", styles["Heading2"]))
    story.append(Paragraph(f"<b>Trained Model:</b> {model_name}", styles["Normal"]))
    story.append(Paragraph(f"<b>Accuracy (Before Mitigation):</b> {accuracy_before:.3f}", styles["Normal"]))
    story.append(Paragraph(f"<b>Accuracy (After Mitigation):</b> {accuracy_after:.3f}", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>3️⃣ Fairness Metrics</b>", styles["Heading2"]))
    data = [
        ["Metric", "Before Mitigation", "After Mitigation"],
        ["Demographic Parity Difference",
         str(round(fairness_before.get("Demographic Parity Difference", 0), 4)),
         str(round(fairness_after.get("Demographic Parity Difference", 0), 4))],
        ["Equal Opportunity Difference",
         str(round(fairness_before.get("Equal Opportunity Difference", 0), 4)),
         str(round(fairness_after.get("Equal Opportunity Difference", 0), 4))],
    ]
    table = Table(data, colWidths=[220, 150, 150])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    story.append(table)
    story.append(Spacer(1, 16))

    story.append(Paragraph("<b>4️⃣ Interpretation</b>", styles["Heading2"]))
    story.append(Paragraph("✅ Smaller differences in Demographic Parity or Equal Opportunity after mitigation indicate improved fairness.", styles["Normal"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>5️⃣ Summary</b>", styles["Heading2"]))
    story.append(Paragraph("Bias mitigation reduced disparities while maintaining performance.", styles["Normal"]))
    story.append(Spacer(1, 20))

    story.append(Paragraph("<font size=9 color='grey'>Generated by BiasScope – AI Fairness Detection & Mitigation Framework.</font>", styles["Normal"]))

    doc = SimpleDocTemplate(output_path, pagesize=A4)
    doc.build(story)
    return output_path
